# Generated by Django 2.2.6 on 2019-10-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20191010_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default-user.jpg', upload_to='profile_pics'),
        ),
    ]
