# Generated by Django 2.2.6 on 2019-10-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20191016_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer identification', max_length=255, verbose_name='Customer name')),
                ('customer_background', models.ImageField(default='default-background.jpg', help_text='Image to fill customers web page background', upload_to='profile_pics', verbose_name='Background')),
                ('customer_logo', models.ImageField(default='default-logo.jpg', help_text='Image to fill customers web page background', upload_to='profile_pics', verbose_name='Background')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_web', models.URLField(blank=True, help_text='Customers website URL', null=True, verbose_name='Customer web')),
                ('Customer', models.ForeignKey(blank=True, help_text='Link to Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer website',
                'verbose_name_plural': 'Customer websites',
            },
        ),
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, help_text='Required: 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=255, null=True, verbose_name='email address')),
                ('is_admin_adr', models.BooleanField(default=False, help_text='Mark special addresses to send additional administration messages. ', verbose_name='admin address')),
                ('Customer', models.ForeignKey(blank=True, help_text='Link to Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer email',
                'verbose_name_plural': 'Customer emails',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(help_text='Street in address', max_length=255, verbose_name='Street')),
                ('address_number', models.CharField(help_text='House number in address', max_length=255, verbose_name='House')),
                ('address_town', models.CharField(help_text='City name in address', max_length=255, verbose_name='City')),
                ('address_zip_code', models.CharField(help_text='ZIP code in address', max_length=255, verbose_name='ZIP')),
                ('Customer', models.ForeignKey(blank=True, help_text='Link to Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Adresses',
            },
        ),
    ]
