# Generated by Django 2.2.6 on 2019-10-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_customeraddress_customeremail_customerweb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customeremail',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerweb',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='projectcustomuser',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Link to Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer'),
        ),
    ]
