# Generated by Django 2.2.6 on 2019-10-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20191016_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPhoneCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_description',
            field=models.TextField(blank=True, help_text='Short text to discribe the Customer.', null=True, verbose_name='Customer description'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_logo',
            field=models.ImageField(default='default-logo.jpg', help_text='Customer logo', upload_to='profile_pics', verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(help_text='Customer phone number', max_length=255, verbose_name='Customer phone')),
                ('customer', models.ForeignKey(blank=True, help_text='Link to Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer phone',
                'verbose_name_plural': 'Customer phones',
            },
        ),
        migrations.CreateModel(
            name='BasicPhoneCategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('cs', 'Czech')], max_length=15, verbose_name='language')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='category')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='customers.BasicPhoneCategory', verbose_name='basicphonecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
