# Generated by Django 2.2.6 on 2019-10-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20191018_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicphonecategorytranslation',
            old_name='type',
            new_name='category',
        ),
    ]
