# Generated by Django 2.2.6 on 2019-10-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20191018_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicphonecategory',
            options={'verbose_name': 'Phone category', 'verbose_name_plural': 'Phone categories'},
        ),
        migrations.RenameField(
            model_name='basicphonecategory',
            old_name='phohe_type',
            new_name='phone_type',
        ),
    ]
