# Generated by Django 2.2.6 on 2019-10-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20191018_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerphone',
            name='category',
            field=models.ForeignKey(default=1, help_text='Category of the phone', on_delete=django.db.models.deletion.CASCADE, to='customers.BasicPhoneCategory', verbose_name='Phone category'),
        ),
    ]
