# Generated by Django 2.2.6 on 2019-10-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_customerphone_desctiption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicphonecategorytranslation',
            name='category',
            field=models.CharField(max_length=50, verbose_name='category'),
        ),
    ]
