# Generated by Django 2.2.6 on 2019-10-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_auto_20191031_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_description',
        ),
        migrations.CreateModel(
            name='CustomerTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('cs', 'Czech')], max_length=15, verbose_name='language')),
                ('customer_description', models.TextField(blank=True, help_text='Short text to discribe the Customer.', null=True, verbose_name='Customer description')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='customers.Customer', verbose_name='customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
