# Generated by Django 2.2.6 on 2019-10-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_auto_20191031_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_DIC',
            field=models.CharField(default='---', help_text='Customer VAT number', max_length=50, verbose_name='VAT'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_ICO',
            field=models.CharField(default='---', help_text='Customer registration number', max_length=50, verbose_name='Registration number'),
        ),
    ]
