# Generated by Django 2.2.6 on 2019-10-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_auto_20191031_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_DIC',
            field=models.CharField(blank=True, help_text='Customer VAT number', max_length=50, null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_ICO',
            field=models.CharField(blank=True, help_text='Customer registration number', max_length=50, null=True, verbose_name='Registration number'),
        ),
    ]
