# Generated by Django 2.2.6 on 2019-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_auto_20191031_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertranslation',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short text to discribe the Customer.', null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='customertranslation',
            name='customer_description',
            field=models.TextField(blank=True, help_text='Text to discribe the Customer extensively.', null=True, verbose_name='Customer description'),
        ),
    ]
