# Generated by Django 2.2.6 on 2019-10-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_auto_20191031_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(help_text='Account number', max_length=50, verbose_name='Account number')),
                ('bank_id', models.CharField(help_text='National identification of the bank', max_length=4, verbose_name='Bank ID')),
                ('iban', models.CharField(help_text='International account identification', max_length=100, verbose_name='IBAN')),
                ('is_prefered', models.BooleanField(default=False, help_text='Preferably use this account.', verbose_name='Prefered account')),
                ('customer', models.ForeignKey(blank=True, help_text='Link to Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer bank account',
                'verbose_name_plural': 'Customer r bank accounts',
            },
        ),
    ]
