# Generated by Django 2.2.6 on 2019-11-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_customerbankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerbankaccount',
            options={'verbose_name': 'Customer bank account', 'verbose_name_plural': 'Customer bank accounts'},
        ),
    ]
