# Generated by Django 2.2.6 on 2019-11-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_auto_20191107_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEstablishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.CharField(help_text='Establishment name', max_length=100, verbose_name='Establishment')),
                ('address_street', models.CharField(help_text='Street in address', max_length=255, verbose_name='Street')),
                ('address_number', models.CharField(help_text='House number in address', max_length=255, verbose_name='House')),
                ('address_town', models.CharField(help_text='City name in address', max_length=255, verbose_name='City')),
                ('address_zip_code', models.CharField(help_text='ZIP code in address', max_length=255, verbose_name='ZIP')),
                ('is_headquarter', models.BooleanField(default=False, help_text='Mark customers headquarter. ', verbose_name='headquarter')),
                ('customer', models.ForeignKey(blank=True, help_text='Link to Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Establishment',
                'verbose_name_plural': 'Establishments',
            },
        ),
    ]
