# Generated by Django 2.2.6 on 2019-11-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_customerestablishments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
