# Generated by Django 2.2.6 on 2019-11-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_delete_customeraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcustomuser',
            options={'permissions': (('is_poweruser', 'custom -- poweruser'), ('is_customer_admin', 'custom -- customer-admin'), ('is_customer_user', 'custom -- customer-user')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
