# Generated by Django 2.2.6 on 2019-11-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_auto_20191120_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcustomuser',
            name='project',
        ),
        migrations.AddField(
            model_name='projectcustomuser',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Link to Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer'),
        ),
    ]
