# Generated by Django 2.2.6 on 2019-11-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_main', '0001_initial'),
        ('customers', '0029_auto_20191120_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomuser',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Link to Project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_main.Project', verbose_name='Project'),
        ),
    ]
