# Generated by Django 2.2.6 on 2019-11-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0030_projectcustomuser_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertranslation',
            name='customer_description',
            field=models.TextField(blank=True, help_text='Text to describe the Customer extensively.', null=True, verbose_name='Customer description'),
        ),
        migrations.AlterField(
            model_name='customertranslation',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short text to describe the Customer.', null=True, verbose_name='Short description'),
        ),
    ]
