# Generated by Django 2.2.6 on 2020-01-21 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integ', '0002_auto_20200121_1017'),
        ('customers', '0031_auto_20191120_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='open_id',
            field=models.ForeignKey(blank=True, help_text='Link to integration key', null=True, on_delete=django.db.models.deletion.CASCADE, to='integ.OpenId', verbose_name='Open id'),
        ),
    ]
