# Generated by Django 2.2.6 on 2019-12-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_auto_20191120_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcustomuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
