# Generated by Django 2.2.6 on 2020-01-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integ', '0002_auto_20200121_1017'),
        ('customers', '0032_userprofile_open_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='open_id',
            field=models.ForeignKey(blank=True, help_text='Link to integration key', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_customers', to='integ.OpenId', verbose_name='Open id'),
        ),
        migrations.AddField(
            model_name='customerestablishments',
            name='open_id',
            field=models.ForeignKey(blank=True, help_text='Link to integration key', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_estab', to='integ.OpenId', verbose_name='Open id'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='open_id',
            field=models.ForeignKey(blank=True, help_text='Link to integration key', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_user_profs', to='integ.OpenId', verbose_name='Open id'),
        ),
    ]
