# Generated by Django 2.2.6 on 2019-12-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0032_auto_20191222_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcustomuser',
            name='email',
            field=models.EmailField(help_text='Required: 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
