# Generated by Django 2.2.6 on 2020-01-29 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0033_auto_20200121_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('cs', 'Czech')], default='cs', help_text='Set the language to communicate with the user', max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default-user.jpg', help_text='Here you can add an image to the profile', upload_to='profile_pics', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Link to patern object', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
