# Generated by Django 2.2.6 on 2020-01-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0033_auto_20200121_1234'),
        ('customers', '0033_auto_20191222_0923'),
    ]

    operations = [
    ]
