# Generated by Django 2.2.6 on 2020-01-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0034_auto_20200129_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeremail',
            name='is_business_adr',
            field=models.BooleanField(default=False, help_text='Business messages will be sent to this address', verbose_name='Business address'),
        ),
        migrations.AddField(
            model_name='customeremail',
            name='is_private_adr',
            field=models.BooleanField(default=False, help_text='This address will not be included in the info. ', verbose_name='Private address'),
        ),
        migrations.AddField(
            model_name='customeremail',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('cs', 'Czech')], default='cs', help_text='Set the language to communicate with the user', max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='customeremail',
            name='is_admin_adr',
            field=models.BooleanField(default=False, help_text='Mark special addresses to send additional administration messages. ', verbose_name='Admin address'),
        ),
    ]
