# Generated by Django 2.2.6 on 2020-01-29 10:45

import customers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0034_merge_20200124_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcustomuser',
            name='email',
            field=models.EmailField(help_text='This acts as the username when logging in.', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='projectcustomuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text="User can log into the website and isn't blocked.", verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='projectcustomuser',
            name='name',
            field=models.CharField(help_text='Only informational.', max_length=255, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='PasswordResetLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('valid_until', models.DateTimeField(default=customers.models.PasswordResetLink.make_expiry_datetime_from_now)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
