# Generated by Django 2.2.6 on 2020-01-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0036_passwordresetlink_used'),
        ('customers', '0035_auto_20200129_0827'),
    ]

    operations = [
    ]
