# Generated by Django 2.2.6 on 2020-01-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenId',
            fields=[
                ('int_id', models.UUIDField(editable=False, help_text='Open key to connect loose parts.', primary_key=True, serialize=False, unique=True, verbose_name='open id')),
            ],
            options={
                'verbose_name': 'Open id',
                'verbose_name_plural': 'Open ids',
            },
        ),
    ]
