# Generated by Django 2.2.6 on 2020-01-21 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openid',
            name='int_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Open key to connect loose parts.', primary_key=True, serialize=False, unique=True, verbose_name='open id'),
        ),
    ]
