# Generated by Django 2.2.6 on 2020-01-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='doc_repository/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='open_id',
            field=models.ForeignKey(blank=True, help_text='Link to integration key', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_docs', to='integ.OpenId', verbose_name='Open id'),
        ),
    ]
