# Generated by Django 2.2.6 on 2020-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_repo', '0002_auto_20200122_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='doc_thumbs/%Y/%m/%d/'),
        ),
    ]
