from django.urls import path
from . import views as ah_views
from . views import (
    AhOfferListView,
    AhAnswerListView,
    AhOfferUpdateView,
    AhOfferDetailView,
    AhOfferDeletelView,
    AhAnswerDeletelView,
    AhOfferInfoView,
    AhDeletelOfferLine,
    AhMatClassDetailView,
    AhOfferCustomerUpdateView,
    AhAnswerDetailView,
    AhAnswerUpdateView,
    AhAnswerCustomerUpdateView,
)


urlpatterns = [
    path('power/offer_list/', AhOfferListView.as_view(), name='ah-offer-list'),
    path('power/answer_list/', AhAnswerListView.as_view(), name='ah-answer-list'),
    path('power/<int:pk>/offer_detail', AhOfferDetailView.as_view(), name='ah-offer-detail'),
    path('power/<int:pk>/offer_update', AhOfferUpdateView.as_view(), name='ah-offer-update'),
    path('power/<int:pk>/cust_update', AhOfferCustomerUpdateView.as_view(), name='ah-offer-customer-update'),
    path('power/<int:pk>/offer_delete', AhOfferDeletelView.as_view(), name='ah-offer-delete'),
    path('power/<int:pk>/answer_delete', AhAnswerDeletelView.as_view(), name='ah-answer-delete'),
    path('power/<int:pk>/offer_update-line/<int:pk2>', ah_views.ah_offer_line_update, name='ah-offer-line-update'),
    path('power/<int:pk>/offer_create-line', ah_views.ah_offer_line_create, name='ah-offer-line-create'),
    path('power/offer_delete-line/<int:pk>', AhDeletelOfferLine.as_view(), name='ah-offer-line-delete'),
    path('power/mat_class/<int:pk>', AhMatClassDetailView.as_view(), name='ah-mat-class-detail'),
    path('power/<int:pk>/answer_update', AhAnswerUpdateView.as_view(), name='ah-answer-update'),
    path('customer/<int:pk>/auction', ah_views.ah_customer_auction, name='ah-customer-auction'),
    path('customer/<int:pk>/create_offer', ah_views.ah_customer_offers_create, name='ah-customer-create-offers'),
    path('customer/<int:pk>/offers_new', ah_views.ah_customer_offers_new, name='ah-customer-new-offers'),
    path('customer/<int:pk>/offer_confirm/<int:pk2>', ah_views.ah_customer_offers_confirm, name='ah-customer-confirm-offers'),
    path('customer/<int:pk>/offer_close/<int:pk2>', ah_views.ah_customer_offers_close, name='ah-customer-close-offers'),
    path('customer/<int:pk>/offer_cancel/<int:pk2>', ah_views.ah_customer_offers_cancel, name='ah-customer-cancel-offers'),
    path('customer/<int:pk>/offers_commited', ah_views.ah_customer_offers_commited, name='ah-customer-commited-offers'),
    path('customer/<int:pk>/offers_accepted', ah_views.ah_customer_offers_accepted, name='ah-customer-accepted-offers'),
    path('customer/<int:pk>/offers_closed', ah_views.ah_customer_offers_closed, name='ah-customer-closed-offers'),
    path('customer/<int:pk>/ready_close', ah_views.ah_customer_offers_ready_close, name='ah-customer-ready_close-offers'),
    path('customer/<int:pk>/offers_canceled', ah_views.ah_customer_offers_canceled, name='ah-customer-canceled-offers'),
    path('customer/<int:pk>/answers_new', ah_views.ah_customer_answer_new, name='ah-customer-new-answers'),
    path('customer/<int:pk>/answer_detail', AhAnswerDetailView.as_view(), name='ah-answer-detail'),
    path('customer/<int:pk>/answer_update', AhAnswerCustomerUpdateView.as_view(), name='ah-answer-customer-update'),
    path('customer/<int:pk>/answers_line_ppu/<int:pk2>', ah_views.ah_answer_line_update_ppu, name='ah-customer-answers-line-ppu'),
    path('customer/<int:pk>/answers_line_total/<int:pk2>', ah_views.ah_answer_line_update_total, name='ah-customer-answers-line-total'),
    path('customer/<int:pk>/answers_confirmed', ah_views.ah_customer_answer_confirmed, name='ah-customer-confirmed-answers'),
    path('customer/<int:pk>/answers_successful', ah_views.ah_customer_answer_successful, name='ah-customer-successful-answers'),
    path('customer/<int:pk>/answers_accepted', ah_views.ah_customer_answer_accepted, name='ah-customer-accepted-answers'),
    path('customer/<int:pk>/answers_closed', ah_views.ah_customer_answer_closed, name='ah-customer-closed-answers'),
    path('customer/<int:pk>/answers_cancelled', ah_views.ah_customer_answer_cancelled, name='ah-customer-cancelled-answers'),
    path('customer/<int:pk>/answers_waiting_offers', ah_views.ah_customer_answer_waiting_offers, name='ah-customer-waiting-offers'),
    path('customer/<int:pk>/offer_info', AhOfferInfoView.as_view(), name='ah-offer-info'),
    path('customer/<int:pk>/answers_create/<int:pk2>', ah_views.ah_customer_answer_create, name='ah-customer-answers-create'),
    path('customer/<int:pk>/answer_confirm/<int:pk2>', ah_views.ah_customer_answer_confirm, name='ah-customer-confirm-answer'),
    path('customer/<int:pk>/answer_accept/<int:pk2>', ah_views.ah_customer_answer_accept, name='ah-customer-accept-answer'),
    path('customer/<int:pk>/answer_cancel/<int:pk2>', ah_views.ah_customer_answer_cancel, name='ah-customer-cancel-answer'),
    path('customer/<int:pk>/answer_close/<int:pk2>', ah_views.ah_customer_answer_close, name='ah-customer-close-answer'),

]
