# Generated by Django 2.2.6 on 2020-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NtfSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_url', models.URLField(blank=True, help_text='URL to connect to SMTP server.', max_length=100, null=True, verbose_name='Smtp addrerss')),
                ('smtp_port', models.IntegerField(blank=True, help_text='Port to connect to SMTP server.', null=True, verbose_name='Smtp port')),
                ('smtp_ssl', models.BooleanField(default=False, help_text='Use SSL connection.', verbose_name='Connect SSL')),
                ('sender_user', models.CharField(blank=True, help_text='User to connect SMTP server.', max_length=100, null=True, verbose_name='Smtp user')),
                ('sender_password', models.CharField(blank=True, help_text='User password to connect SMTP server.', max_length=50, null=True, verbose_name='Smtp user password')),
            ],
            options={
                'verbose_name': 'NtfSetup',
                'verbose_name_plural': 'NtfSetup',
            },
        ),
    ]
