# Generated by Django 2.2.6 on 2020-01-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200127_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntfsetup',
            name='smtp_url',
            field=models.CharField(blank=True, help_text='URL to connect to SMTP server.', max_length=100, null=True, verbose_name='Smtp addrerss'),
        ),
    ]
