# Generated by Django 2.2.6 on 2020-01-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200127_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_key', models.CharField(blank=True, default='fallback', help_text='Key to identify the template', max_length=20, null=True, verbose_name='Template key')),
            ],
            options={
                'verbose_name_plural': 'Message Templates',
                'verbose_name': 'Message Template',
            },
        ),
        migrations.CreateModel(
            name='MessTempTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('cs', 'Czech')], max_length=15, verbose_name='language')),
                ('subject', models.CharField(blank=True, help_text='Message subject.', max_length=200, null=True, verbose_name='Subject')),
                ('body', models.TextField(blank=True, help_text='Message body (playn-text/html).', null=True, verbose_name='Body')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notification.MessTemp', verbose_name='messtemp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
