# Generated by Django 2.2.6 on 2020-01-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_messtemp_temp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messtemp',
            name='temp_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('html', 'Html')], default='text', help_text='Template type (text/html)', max_length=10, null=True, verbose_name='Template type'),
        ),
    ]
