# Generated by Django 2.2.6 on 2019-11-22 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0031_auto_20191120_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Offers description', max_length=200, null=True, verbose_name='Description')),
                ('is_new', models.BooleanField(default=True, help_text='New created offer. ', verbose_name='New')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Offers is confirmed by owner. ', verbose_name='Confirmed')),
                ('is_in_process', models.BooleanField(default=False, help_text='Offers is in auction. ', verbose_name='In process')),
                ('is_closed', models.BooleanField(default=False, help_text='Mark closed offers. ', verbose_name='Closed')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Mark cancelled offers. ', verbose_name='Cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Link to Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_changed_offers', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('creator', models.ForeignKey(help_text='Link to Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('owner', models.ForeignKey(help_text='Link to Owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_offers', to='customers.Customer', verbose_name='Owner')),
            ],
            options={
                'verbose_name_plural': 'Offers',
                'verbose_name': 'Offer',
            },
        ),
    ]
