# Generated by Django 2.2.6 on 2019-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0002_auto_20191122_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahoffer',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='inprocess_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
