# Generated by Django 2.2.6 on 2019-11-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_auto_20191120_1453'),
        ('auction_house', '0003_auto_20191122_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahoffer',
            name='offered_to',
            field=models.ManyToManyField(help_text='List of customers who received the offer', null=True, related_name='receive_offers', to='customers.Customer', verbose_name='Offered to'),
        ),
    ]
