# Generated by Django 2.2.6 on 2019-11-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0005_auto_20191125_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahoffer',
            name='offered_to',
            field=models.ManyToManyField(blank=True, help_text='List of customers who received the offer', related_name='receive_offers', to='customers.Customer', verbose_name='Offered to'),
        ),
    ]
