# Generated by Django 2.2.6 on 2019-11-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0006_auto_20191125_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhOfferLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Offers description', max_length=200, null=True, verbose_name='Description')),
                ('offer', models.ForeignKey(blank=True, help_text='Link to Offer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='auction_house.AhOffer', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'Offer line',
                'verbose_name_plural': 'Offer lines',
            },
        ),
    ]
