# Generated by Django 2.2.6 on 2019-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0007_ahofferline'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahofferline',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
