# Generated by Django 2.2.6 on 2019-11-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0008_ahofferline_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhMatClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='Name of the material class', max_length=200, unique=True, verbose_name='Material class name')),
                ('measurement_unit', models.CharField(help_text='Units in which material is entered', max_length=200, unique=True, verbose_name='Measurement unit')),
            ],
            options={
                'verbose_name': 'Material class',
                'verbose_name_plural': 'Material classes',
            },
        ),
        migrations.AlterField(
            model_name='ahofferline',
            name='description',
            field=models.CharField(blank=True, help_text='Offers line description', max_length=200, null=True, verbose_name='Description'),
        ),
    ]
