# Generated by Django 2.2.6 on 2019-11-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0009_auto_20191126_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhMatClassTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('cs', 'Czech')], max_length=15, verbose_name='language')),
                ('display_name', models.CharField(help_text='Name of the material class for displaying', max_length=200, unique=True, verbose_name='Material class display name')),
                ('mat_class_description', models.TextField(blank=True, help_text='Text to describe the material class.', null=True, verbose_name='Material class description')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='auction_house.AhMatClass', verbose_name='ahmatclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
