# Generated by Django 2.2.6 on 2019-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0011_auto_20191126_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahmatclass',
            name='measurement_unit',
            field=models.CharField(help_text='Units in which material is entered', max_length=10, unique=True, verbose_name='Measurement unit'),
        ),
    ]
