# Generated by Django 2.2.6 on 2019-11-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_auto_20191120_1453'),
        ('auction_house', '0012_auto_20191126_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahofferline',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Quantity of material', max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.CreateModel(
            name='AhAnsver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Offers description', max_length=200, null=True, verbose_name='Description')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final price for the answer', max_digits=10, null=True, verbose_name='Total price')),
                ('ah_offer', models.ForeignKey(help_text='Link to Offer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ansvers', to='auction_house.AhOffer', verbose_name='Offer')),
                ('owner', models.ForeignKey(help_text='Link to Owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_ansvers', to='customers.Customer', verbose_name='Owner')),
            ],
        ),
    ]
