# Generated by Django 2.2.6 on 2019-12-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0014_auto_20191129_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahanswer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.CreateModel(
            name='AhAnswerLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppu', models.DecimalField(blank=True, decimal_places=2, help_text='Price for one measurement unit', max_digits=7, null=True, verbose_name='Price per unit')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final price for the line', max_digits=10, null=True, verbose_name='Total price')),
                ('answer', models.ForeignKey(help_text='Link to Answer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_lines', to='auction_house.AhAnswer', verbose_name='Answer')),
                ('offer_line', models.ForeignKey(help_text='Link to line of offer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_lines', to='auction_house.AhOfferLine', verbose_name='Offer line')),
            ],
            options={
                'verbose_name_plural': 'Answer lines',
                'verbose_name': 'Answer line',
            },
        ),
    ]
