# Generated by Django 2.2.6 on 2019-12-03 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction_house', '0015_auto_20191202_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahanswer',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='Link to user made last change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_changed_answers', to=settings.AUTH_USER_MODEL, verbose_name='Last change'),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='creator',
            field=models.ForeignKey(help_text='Link to Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_answers', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Mark cancelled answers. ', verbose_name='Cancelled'),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Mark closed answers. ', verbose_name='Closed'),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Answer is confirmed by owner. ', verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='is_new',
            field=models.BooleanField(default=True, help_text='New created offer. ', verbose_name='New'),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='is_successful',
            field=models.BooleanField(default=False, help_text='Mark successful answers. ', verbose_name='Successful'),
        ),
    ]
