# Generated by Django 2.2.6 on 2019-12-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0016_auto_20191203_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahanswer',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ahanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
