# Generated by Django 2.2.6 on 2019-12-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0017_auto_20191203_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahoffer',
            old_name='inprocess_at',
            new_name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='is_in_process',
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='auction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Mark offers accepted by the buyer.', verbose_name='Accepted'),
        ),
    ]
