# Generated by Django 2.2.6 on 2019-12-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0019_auto_20191204_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahanswer',
            name='owner',
            field=models.ForeignKey(help_text='Link to Owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_answers', to='customers.Customer', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='ahoffer',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted at'),
        ),
        migrations.AlterField(
            model_name='ahoffer',
            name='auction_date',
            field=models.DateField(blank=True, help_text='Date of auction', null=True, verbose_name='Auction date'),
        ),
        migrations.AlterField(
            model_name='ahoffer',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Canceled at'),
        ),
        migrations.AlterField(
            model_name='ahoffer',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed at'),
        ),
        migrations.AlterField(
            model_name='ahoffer',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed at'),
        ),
        migrations.AlterField(
            model_name='ahoffer',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at'),
        ),
        migrations.AlterField(
            model_name='ahoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of the delivery', verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='ahoffer',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Date of the delivery', null=True, verbose_name='Delivery date'),
        ),
    ]
