# Generated by Django 2.2.6 on 2019-12-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0021_auto_20191205_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahanswer',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='Accepted from...', null=True, verbose_name='Accepted at'),
        ),
        migrations.AddField(
            model_name='ahanswer',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Mark accepted answers. ', verbose_name='Accepted'),
        ),
        migrations.AlterField(
            model_name='ahanswer',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='Canceled from...', null=True, verbose_name='Canceled at'),
        ),
        migrations.AlterField(
            model_name='ahanswer',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Closed from...', null=True, verbose_name='Closed at'),
        ),
        migrations.AlterField(
            model_name='ahanswer',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Link to Offer', null=True, verbose_name='Offer'),
        ),
    ]
