# Generated by Django 2.2.6 on 2019-12-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0022_auto_20191206_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahoffer',
            name='is_ready_close',
            field=models.BooleanField(default=False, help_text='Mark ready to close offers.', verbose_name='Ready to close'),
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='ready_close_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ready to close at'),
        ),
        migrations.AlterField(
            model_name='ahanswer',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Confirmed from...', null=True, verbose_name='Confirmed at'),
        ),
    ]
