# Generated by Django 2.2.6 on 2019-12-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0023_auto_20191209_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahanswer',
            name='is_bound',
            field=models.BooleanField(default=False, help_text='Mark bound answers. ', verbose_name='Bound'),
        ),
    ]
