# Generated by Django 2.2.6 on 2020-01-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0024_ahanswer_is_bound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahoffer',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='is_ready_close',
        ),
        migrations.RemoveField(
            model_name='ahoffer',
            name='ready_close_at',
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='auction_end',
            field=models.DateTimeField(blank=True, help_text='From this time is auction URL closed', null=True, verbose_name='Auction end'),
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='auction_start',
            field=models.DateTimeField(blank=True, help_text='From this time is auction URL accessible', null=True, verbose_name='Auction start'),
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='auction_url',
            field=models.URLField(blank=True, help_text='Online auction url', null=True, verbose_name='Auction URL'),
        ),
        migrations.AddField(
            model_name='ahoffer',
            name='minimal_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final minimal price', max_digits=10, null=True, verbose_name='Minimal total price'),
        ),
        migrations.AddField(
            model_name='ahofferline',
            name='minimal_ppu',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimal price for one measurement unit', max_digits=7, verbose_name='Minimal price per unit'),
        ),
    ]
