# Generated by Django 2.2.6 on 2020-01-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0025_auto_20200107_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahanswer',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='ahanswer',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='ahanswer',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='ahanswer',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='ahanswer',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='ahanswer',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='ahanswer',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='ahanswer',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='ahanswer',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='ahanswer',
            name='is_successful',
        ),
    ]
