# Generated by Django 2.2.6 on 2020-01-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integ', '0002_auto_20200121_1017'),
        ('auction_house', '0026_auto_20200108_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahoffer',
            name='open_id',
            field=models.ForeignKey(blank=True, help_text='Link to integration key', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_offers', to='integ.OpenId', verbose_name='Open id'),
        ),
    ]
