# Generated by Django 2.2.6 on 2020-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0029_ahanswer_open_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahoffer',
            name='offered_to',
            field=models.ManyToManyField(blank=True, help_text='List of customers who recieved the offer', related_name='recieve_offers', to='customers.Customer', verbose_name='Offered to'),
        ),
    ]
