# Generated by Django 2.2.9 on 2020-02-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0030_auto_20200203_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahanswer',
            name='auction_url',
            field=models.URLField(blank=True, help_text='Online auction url', null=True, verbose_name='Auction URL'),
        ),
    ]
