# Generated by Django 2.2.9 on 2020-02-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0031_ahanswer_auction_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of offer creation', verbose_name='Created at'),
        ),
    ]
