# Generated by Django 2.2.9 on 2020-02-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0032_auto_20200210_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahofferline',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='Quantity of material', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='ahofferline',
            name='description',
            field=models.CharField(help_text='Offers line description', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ahofferline',
            name='mat_class',
            field=models.ForeignKey(help_text='Link to Material class', on_delete=django.db.models.deletion.CASCADE, related_name='used_lines', to='auction_house.AhMatClass', verbose_name='Material class'),
        ),
        migrations.AlterField(
            model_name='ahofferline',
            name='offer',
            field=models.ForeignKey(help_text='Link to Offer', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='auction_house.AhOffer', verbose_name='Offer'),
        ),
    ]
