# Generated by Django 2.2.10 on 2020-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0033_auto_20200219_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahoffer',
            name='description',
            field=models.CharField(help_text='Offers description', max_length=200, null=True, verbose_name='Description'),
        ),
    ]
