# Generated by Django 2.2.10 on 2020-03-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0034_auto_20200310_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Catalog entry code', max_length=25, null=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, help_text='Catalog entry description', max_length=200, null=True, verbose_name='Description')),
                ('type', models.CharField(blank=True, help_text='Catalog entry Type', max_length=1, null=True, verbose_name='Type')),
                ('is_group', models.BooleanField(default=False, help_text='Mark groups for other catalog entries. ', verbose_name='Is group')),
                ('is_dangerous', models.BooleanField(default=False, help_text='Mark groups for other catalog entries. ', verbose_name='Is group')),
                ('non_actual', models.BooleanField(default=False, help_text='Mark not actual entries. ', verbose_name='Not actual')),
            ],
            options={
                'verbose_name': 'Catalog entry',
                'verbose_name_plural': 'Catalog entries',
            },
        ),
    ]
