# Generated by Django 2.2.10 on 2020-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0035_catalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='type',
            new_name='str_type',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='is_dangerous',
            field=models.BooleanField(default=False, help_text='Mark dangerous catalog entries. ', verbose_name='Is dangerous'),
        ),
    ]
