# Generated by Django 2.2.10 on 2020-03-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0038_ahmatclass_non_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahmatclass',
            name='c_entry',
            field=models.ForeignKey(help_text='Link to the Catalog', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='auction_house.Catalog', verbose_name='Catalog entry'),
        ),
    ]
