# Generated by Django 2.2.10 on 2020-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0039_auto_20200316_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahmatclass',
            name='measurement_unit',
            field=models.CharField(help_text='Units in which material is entered', max_length=10, verbose_name='Measurement unit'),
        ),
    ]
