# Generated by Django 2.2.10 on 2020-03-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0040_auto_20200316_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahmatclass',
            name='c_entry',
            field=models.ForeignKey(help_text='Link to the Catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='auction_house.Catalog', verbose_name='Catalog entry'),
        ),
    ]
