# Generated by Django 2.2.10 on 2020-03-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0041_auto_20200316_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahmatclass',
            name='base_description',
            field=models.TextField(blank=True, help_text='Text to describe the material class for quick access.', null=True, verbose_name='Material class quick description'),
        ),
    ]
