# Generated by Django 2.2.6 on 2019-11-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_background',
            field=models.ImageField(default='default-project-background.jpg', help_text='Image to fill Project web page background', upload_to='project_main', verbose_name='Background'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, help_text='Text to describe project.', null=True, verbose_name='Project description'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(default='default-project-logo.jpg', help_text='Project logo', upload_to='project_main', verbose_name='Logo'),
        ),
    ]
