# Generated by Django 2.2.6 on 2019-11-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_main', '0003_staticpage_staticpagetranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpagetranslation',
            name='page_name',
        ),
        migrations.RemoveField(
            model_name='staticpagetranslation',
            name='page_title',
        ),
    ]
