# Generated by Django 2.2.6 on 2019-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_main', '0004_auto_20191121_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpagetranslation',
            name='page_title',
            field=models.TextField(blank=True, help_text='Static page title.', null=True, verbose_name='Page title'),
        ),
    ]
