# Generated by Django 2.2.6 on 2019-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_main', '0006_auto_20191121_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='sequence',
            field=models.IntegerField(default=0, help_text='Page order in the menu', verbose_name='Sequence number'),
        ),
        migrations.AddField(
            model_name='staticpagetranslation',
            name='page_name',
            field=models.CharField(blank=True, help_text='Static page name', max_length=50, null=True, verbose_name='Page name'),
        ),
    ]
