# Generated by Django 2.2.6 on 2019-12-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_main', '0007_auto_20191122_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(default='default-project-logo.png', help_text='Project logo', upload_to='project_main', verbose_name='Logo'),
        ),
    ]
