# Generated by Django 2.2.6 on 2020-01-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_main', '0008_auto_20191222_1350'),
        ('project_main', '0008_auto_20200106_0941'),
    ]

    operations = [
    ]
