# Generated by Django 2.2.6 on 2020-01-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepstate',
            name='previous',
            field=models.ForeignKey(blank=True, help_text='Previous state', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_states', to='state_wf.StepState', verbose_name='Previous'),
        ),
        migrations.AddField(
            model_name='stepstatetranslation',
            name='state_description',
            field=models.CharField(blank=True, help_text='Short description.', max_length=100, null=True, verbose_name='State description'),
        ),
        migrations.AddField(
            model_name='stepstatetranslation',
            name='state_template_question',
            field=models.TextField(blank=True, help_text='Template text to query state change.', null=True, verbose_name='State template question'),
        ),
        migrations.AddField(
            model_name='stepstatetranslation',
            name='state_template_text',
            field=models.TextField(blank=True, help_text='Text to describe the state change.', null=True, verbose_name='State template text'),
        ),
        migrations.AlterField(
            model_name='stepstatetranslation',
            name='state_name',
            field=models.CharField(blank=True, help_text='Display name of state.', max_length=50, null=True, verbose_name='State name'),
        ),
    ]
