# Generated by Django 2.2.6 on 2020-01-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0002_auto_20200106_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepstatetranslation',
            name='state_button_text',
            field=models.CharField(blank=True, help_text='Activating button text.', max_length=50, null=True, verbose_name='State button text'),
        ),
    ]
