# Generated by Django 2.2.6 on 2020-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0003_stepstatetranslation_state_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepstate',
            name='security_level',
            field=models.IntegerField(default=0, help_text='Abstract security level', verbose_name='Security level'),
        ),
    ]
