# Generated by Django 2.2.6 on 2020-01-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0004_stepstate_security_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepstatetranslation',
            name='state_template_confitm_button',
            field=models.CharField(blank=True, help_text='Template state confirmation button text.', max_length=50, null=True, verbose_name='State template confirm button'),
        ),
    ]
