# Generated by Django 2.2.6 on 2020-01-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0005_stepstatetranslation_state_template_confitm_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepstate',
            name='previous',
        ),
        migrations.AddField(
            model_name='stepstate',
            name='previous',
            field=models.ManyToManyField(blank=True, help_text='Previous state', related_name='previous_states', to='state_wf.StepState', verbose_name='Previous'),
        ),
    ]
