# Generated by Django 2.2.6 on 2020-01-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0006_auto_20200106_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepstate',
            name='manual_set',
            field=models.BooleanField(default=False, help_text='State chcange manual. ', verbose_name='Manual set'),
        ),
    ]
