# Generated by Django 2.2.6 on 2020-01-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0009_auto_20200107_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepstatetranslation',
            name='is_allerrt',
        ),
        migrations.AddField(
            model_name='stepstate',
            name='is_alert_button',
            field=models.BooleanField(default=False, help_text='Show starting button like alert. ', verbose_name='Alert button'),
        ),
    ]
