# Generated by Django 2.2.6 on 2020-01-07 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_house', '0024_ahanswer_is_bound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('state_wf', '0010_auto_20200107_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_link', models.ForeignKey(help_text='Link to answer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_steps', to='auction_house.AhAnswer', verbose_name='Answer')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Link to creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_steps', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('offer_link', models.ForeignKey(help_text='Link to offer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_steps', to='auction_house.AhOffer', verbose_name='Offer')),
                ('state', models.ForeignKey(help_text='Link to step state', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='state_wf.StepState', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
    ]
