# Generated by Django 2.2.6 on 2020-01-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0011_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='answer_link',
            field=models.ForeignKey(blank=True, help_text='Link to answer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_steps', to='auction_house.AhAnswer', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='step',
            name='offer_link',
            field=models.ForeignKey(blank=True, help_text='Link to offer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_steps', to='auction_house.AhOffer', verbose_name='Offer'),
        ),
    ]
