# Generated by Django 2.2.6 on 2020-01-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0012_auto_20200107_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepstate',
            name='previous',
            field=models.ManyToManyField(blank=True, help_text='Previous state', related_name='next_states', to='state_wf.StepState', verbose_name='Previous'),
        ),
    ]
