# Generated by Django 2.2.6 on 2020-01-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0013_auto_20200108_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepstate',
            name='group_key',
            field=models.IntegerField(default=1, help_text='Key for the division of states into groups. ', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='stepstate',
            name='group_serial_number',
            field=models.IntegerField(default=0, help_text='Serial number inside the group. ', verbose_name='Serial number'),
        ),
    ]
