# Generated by Django 2.2.6 on 2020-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0014_auto_20200113_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepstatetranslation',
            name='state_name_plural',
            field=models.CharField(blank=True, help_text='Display name of state in plural.', max_length=50, null=True, verbose_name='State name plural'),
        ),
    ]
