# Generated by Django 2.2.6 on 2020-01-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0015_stepstatetranslation_state_name_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepstate',
            name='manual_set',
            field=models.BooleanField(default=False, help_text='State change manually.', verbose_name='Manual set'),
        ),
    ]
