# Generated by Django 2.2.6 on 2020-01-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0016_auto_20200116_1337'),
        ('state_wf', '0016_auto_20200121_0907'),
    ]

    operations = [
    ]
