# Generated by Django 2.2.6 on 2020-01-30 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20200129_0809'),
        ('state_wf', '0017_auto_20200130_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepstate',
            old_name='send_htf',
            new_name='send_ntf',
        ),
        migrations.AddField(
            model_name='stepstate',
            name='ntf_template',
            field=models.ForeignKey(blank=True, help_text='Notification template used to generate message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_states', to='notification.MessTemp', verbose_name='Template'),
        ),
    ]
