# Generated by Django 2.2.6 on 2020-01-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_wf', '0017_merge_20200124_1124'),
        ('state_wf', '0018_auto_20200130_0808'),
    ]

    operations = [
    ]
